# Generated by Django 6.0.4 on 2026-04-09 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signing', '0002_alter_signingrequest_id_signaturerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], max_length=20)),
                ('is_signature_valid', models.BooleanField(default=False)),
                ('is_hash_match', models.BooleanField(default=False)),
                ('signer_subject', models.CharField(blank=True, max_length=255)),
                ('signer_serial', models.CharField(blank=True, max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('signature_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_result', to='signing.signaturerecord')),
            ],
        ),
    ]
