# Generated by Django 6.0.5 on 2026-06-01 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0006_signingrequest_expires_at_signingrequest_nonce_and_more'),
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_certificate_pem', models.TextField(blank=True)),
                ('certificate_chain_pem', models.TextField(blank=True)),
                ('crl_pem', models.TextField(blank=True)),
                ('ocsp_response_base64', models.TextField(blank=True)),
                ('timestamp_token_base64', models.TextField(blank=True)),
                ('evidence_hash', models.CharField(blank=True, max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('signature_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_evidence', to='signing.signaturerecord')),
            ],
        ),
    ]
