# Generated by Django 6.0.4 on 2026-04-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usercertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercertificate',
            name='key_storage_type',
            field=models.CharField(choices=[('file', 'File PEM'), ('softhsm', 'SoftHSM PKCS#11')], default='softhsm', max_length=20),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='pkcs11_key_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='pkcs11_key_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='pkcs11_slot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='pkcs11_token_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usercertificate',
            name='private_key_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
