# Generated by Django 6.0.6 on 2026-06-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='current_signed_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/pades/current/'),
        ),
        migrations.AddField(
            model_name='document',
            name='final_signed_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/pades/final/'),
        ),
    ]
