# Generated by Django 6.0.6 on 2026-06-04 01:14

import uuid
from django.db import migrations, models

def gen_uuid(apps, schema_editor):
    Document = apps.get_model("documents", "Document")
    for doc in Document.objects.all():
        doc.verification_id = uuid.uuid4()
        doc.save(update_fields=["verification_id"])

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_current_signed_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="form_type",
            field=models.CharField(blank=True, default="uploaded_document", max_length=50),
        ),
        # Bước 1: thêm field KHÔNG unique, cho phép null tạm
        migrations.AddField(
            model_name="document",
            name="verification_id",
            field=models.UUIDField(null=True, editable=False),
        ),
        # Bước 2: chạy hàm gen UUID riêng cho từng row
        migrations.RunPython(gen_uuid, migrations.RunPython.noop),
        # Bước 3: giờ mới đặt unique=True
        migrations.AlterField(
            model_name="document",
            name="verification_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
    ]
