# Generated by Django 6.0.6 on 2026-06-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_form_type_document_verification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='final_signed_pdf_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
