# Generated by Django 6.0.6 on 2026-06-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_final_signed_pdf_sha256'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='current_signed_pdf_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
