# Generated by Django 6.0.5 on 2026-06-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('document_upload', 'Document Upload'), ('signing_request_created', 'Signing Request Created'), ('remote_signed', 'Remote Signed'), ('client_signed', 'Client Signed'), ('officer_approval_signed', 'Officer Approval Signed'), ('verification_run', 'Verification Run'), ('identity_verified', 'Identity Verified'), ('identity_rejected', 'Identity Rejected'), ('certificate_issued', 'Certificate Issued')], max_length=100),
        ),
    ]
