# Generated by Django 6.0.4 on 2026-04-09 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signingrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='SignatureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_value', models.TextField()),
                ('certificate_subject', models.CharField(blank=True, max_length=255)),
                ('certificate_serial', models.CharField(blank=True, max_length=255)),
                ('algorithm', models.CharField(default='RSA-SHA256', max_length=100)),
                ('signed_hash', models.CharField(max_length=64)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('signing_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature_record', to='signing.signingrequest')),
            ],
        ),
    ]
