# Generated by Django 6.0.4 on 2026-04-09 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0002_alter_signingrequest_id_signaturerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturerecord',
            name='certificate_pem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='signingrequest',
            name='signer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signing_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
