# Generated by Django 5.1.7 on 2026-04-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0003_signaturerecord_certificate_pem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturerecord',
            name='timestamp_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='signaturerecord',
            name='timestamp_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='signaturerecord',
            name='timestamp_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='signaturerecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='signingrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
