# Generated by Django 6.0.5 on 2026-06-01 09:35

import signing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0005_alter_signaturerecord_id_alter_signingrequest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='signingrequest',
            name='expires_at',
            field=models.DateTimeField(default=signing.models.default_signing_request_expiry),
        ),
        migrations.AddField(
            model_name='signingrequest',
            name='nonce',
            field=models.CharField(db_index=True, default=signing.models.default_signing_request_nonce, max_length=64),
        ),
        migrations.AddField(
            model_name='signingrequest',
            name='strong_auth_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signingrequest',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
