# Generated by Django 6.0.6 on 2026-06-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0006_signingrequest_expires_at_signingrequest_nonce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signingrequest',
            name='client_token',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='signingrequest',
            name='client_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signaturerecord',
            name='algorithm',
            field=models.CharField(default='ML-DSA-65', max_length=100),
        ),
    ]
