# Generated by Django 6.0.6 on 2026-06-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0007_signingrequest_client_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signingrequest',
            name='auth_method',
            field=models.CharField(default='password_session', max_length=100),
        ),
        migrations.AddField(
            model_name='signingrequest',
            name='consent_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='signingrequest',
            name='consent_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='signingrequest',
            name='purpose',
            field=models.CharField(choices=[('citizen_self_sign', 'Citizen self sign'), ('officer_approval', 'Officer approval'), ('remote_tsp_sign', 'Remote TSP sign')], default='citizen_self_sign', max_length=50),
        ),
        migrations.AddField(
            model_name='signingrequest',
            name='request_document_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='signingrequest',
            name='request_nonce',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='signingrequest',
            name='requester_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signingrequest',
            name='requester_user_agent',
            field=models.TextField(blank=True),
        ),
    ]
