# Generated by Django 6.0.6 on 2026-06-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0008_signingrequest_auth_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signingrequest',
            name='purpose',
            field=models.CharField(choices=[('citizen_local_sign', 'Citizen local signing'), ('citizen_remote_sign', 'Citizen remote signing via TSP'), ('officer_approval', 'Officer approval')], default='citizen_local_sign', max_length=50),
        ),
    ]
