# Generated by Django 6.0.6 on 2026-06-16 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0009_alter_signingrequest_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPadesSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared_pdf', models.FileField(blank=True, null=True, upload_to='documents/pades/prepared/')),
                ('prepared_pdf_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('document_digest', models.CharField(blank=True, default='', max_length=128)),
                ('signed_attrs_b64', models.TextField(blank=True, default='')),
                ('prepared_digest_blob', models.BinaryField(blank=True, null=True)),
                ('field_name', models.CharField(blank=True, default='', max_length=120)),
                ('bytes_reserved', models.PositiveIntegerField(default=65536)),
                ('digest_algorithm', models.CharField(default='sha512', max_length=30)),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('completed', 'Completed'), ('failed', 'Failed')], default='prepared', max_length=30)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('signing_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_pades_session', to='signing.signingrequest')),
            ],
        ),
    ]
