# Generated by Django 6.0.6 on 2026-06-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0010_clientpadessession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturerecord',
            name='signed_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
