# Generated by Django 6.0.6 on 2026-06-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0011_alter_signaturerecord_signed_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='signingrequest',
            name='paired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signingrequest',
            name='pairing_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signingrequest',
            name='pairing_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signingrequest',
            name='pairing_code_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='signingrequest',
            name='pairing_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signingrequest',
            name='pairing_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('waiting_device', 'Waiting for device'), ('device_paired', 'Device paired'), ('confirmed', 'Confirmed'), ('consumed', 'Consumed'), ('expired', 'Expired'), ('failed', 'Failed')], db_index=True, default='not_started', max_length=30),
        ),
        migrations.AddField(
            model_name='signingrequest',
            name='signer_device_last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signingrequest',
            name='signer_device_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='signingrequest',
            name='signer_device_public_key_pem',
            field=models.TextField(blank=True),
        ),
    ]
