openssl_conf = openssl_init

[ openssl_init ]

[ tsa ]
default_tsa = tsa_config1

[ tsa_config1 ]
dir = /app/pki-lab/tsa
serial = $dir/tsaserial
crypto_device = builtin
signer_cert = $dir/certs/tsa.crt
certs = /app/pki-lab/certs/rootCA.crt
signer_key = $dir/private/tsa.key
signer_digest = sha256
default_policy = 1.2.3.4.1
other_policies = 1.2.3.4.5.6
digests = sha256, sha384, sha512
accuracy = secs:1, millisecs:500, microsecs:100
clock_precision_digits = 0
ordering = yes
tsa_name = yes
ess_cert_id_chain = no
ess_cert_id_alg = sha256